#ifndef COMPUTE_REQUIRED_BYTES_FOR_ENCODED_SYMBOLS_H
#define COMPUTE_REQUIRED_BYTES_FOR_ENCODED_SYMBOLS_H

size_t computeRequiredBytesForEncodedSymbols(size_t lengthOfBytesWithItsFrequencies);

#endif
